port: 40001

# Build settings
markdown: kramdown

title: General SQL Parser Support Center
description: Documents and demos of General SQL Parser
google_analytics: 
show_downloads: true
theme: jekyll-theme-time-machine