port: 40001

# Build settings
markdown: kramdown

title: General SQL Parser
description: Documents and demos of General SQL Parser
google_analytics: 
show_downloads: false
theme: jekyll-theme-time-machine